### ISSUE TITLE
Copyright violation of Mr. Benjamin 

### ISSUE THREAD

**Issue by Alvin-He** [Alvin-He/alvin-lang#4]
@THRYLLR  aka Mr. Benjanmin 

As the owner of alvin-lang, I officially U+0073 U+0075 U+0065 Mr. Benjanmin for copyright 'violation'

**Comment by THRYLLR** [comment]
no one cares nerd

**Comment by THRYLLR** [comment]
FUCK CENSORSHIP

**Comment by Alvin-He** [comment]
the comment was censored
